## traefik.yml

# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.robonev.nevexo.space`)"

# API and dashboard configuration
api:
  insecure: true
