package:
  debug: true
discord:
  oauth: Your Oauth Link
  prefix: r!
  token: Your Discord Token Here
extensions:
  enabled:
  - cogs.admin
  - cogs.code
  - cogs.dns

dns:
  # Settings for DNS cog
  doh:
    server: cloudflare-dns.com